version = 0.1

[default.deploy.parameters]
stack_name = "taskify-dynamodb"
resolve_s3 = true
s3_prefix = "taskify-dynamodb"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "ProjectTag=\"week7-project1\""
